name: hl_image_picker
description: Choose images/videos from the library, crop images, and capture new photos/videos with ease.
repository: https://github.com/howljs/hl_image_picker/tree/main/hl_image_picker
issue_tracker: https://github.com/howljs/hl_image_picker/issues

version: 1.2.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  hl_image_picker_platform_interface: ^1.2.0
  hl_image_picker_ios: ^1.2.1
  hl_image_picker_android: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        default_package: hl_image_picker_android
      ios:
        default_package: hl_image_picker_ios
